version: '2'
services:
  proxy:
    image: nginx
    volumes:
      - ./env/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    image: brucepc/symfony
    ports:
      - 9000
    volumes:
      - ./src:/var/www:rw
    environment:
      - SYMFONY_ENV:dev
      - SYMFONY_DEBUG:1
  db:
    image: postgres
    environment:
      - POSTGRES_USER:taskmngr
      - POSTGRES_PASSWORD:changetoprodution